### ISSUE TITLE
Can we receive 300 character (300 bytes) at RS485 receive pin ??

### ISSUE THREAD

**Issue by thanthdinesh** [xanthium-enterprises/Cross-Platform-RS485-Programming-C#1]

**Comment by thanthdinesh** [comment]
suppose my receive bytes is more than 256 bytes so how to set  SerialPortSettings.c_cc[VMIN] =  ?

**Comment by xanthium-enterprises** [comment]
SerialPortSettings.c_cc[VMIN] =255
is the maximum allowed value.
You can read it in two batches,

check this link to know more 
http://unixwiz.net/techtips/termios-vmin-vtime.html

**Comment by xanthium-enterprises** [comment]
Try using two read calls one after the other

**Comment by thanthdinesh** [comment]
Thank you sir ,I will try this

**Comment by thanthdinesh** [comment]
It is working fine
Thank you sir

**Comment by thanthdinesh** [comment]
I try this but some time it take previous value also so how it handle ??

**Comment by xanthium-enterprises** [comment]
try this

 1. read the data
 2. save the data to a variable1 or array1
 3. clear the UART buffer
 4. read the data
 5. save the data to a variable2 or array2 again
